version: '3.9'

services:
  # Frontend React sans Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://fultang.ddns.net:8011/api/v1
        VITE_APP_VERSION: 1.0.0
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
